name: Bus Data Pipeline

on:
   schedule:
    - cron: '0 6 * * *' # Every 30 minutes
  workflow_dispatch:      # Manual trigger

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # Indispensable pour les nouvelles versions de pandas/supabase
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install requests geopandas shapely supabase pandas gtfs-realtime-bindings protobuf==4.25.1
      - name: Run collector
        env:
          TRANSLINK_API_KEY: ${{ secrets.TRANSLINK_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python src/fetch_bus_data.py
