name: Initialize Map Data
on: workflow_dispatch # Allows you to click a button to run it

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install osmnx geopandas pandas
      - name: Run generator
        run: python src/generate_map.py
      - name: Commit and Push map
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main --rebase  # Récupère les changements distants et remet ton commit par-dessus
          git add data/metro_vancouver_map.geojson
          git commit -m "Log: Update Metro Vancouver map" || echo "No changes to commit"
          git push origin main
